#ifndef __ANALYZE_H
# define __ANALYZE_H
#define TRC_GEN_MAIN     0
#define TRC_SCHED_MAIN   1
#define TRC_DOM0OP_MAIN  2
#define TRC_HVM_MAIN     3
#define TRC_MEM_MAIN     4
#define TRC_PV_MAIN      5
#define TRC_SHADOW_MAIN  6
#define TRC_PM_MAIN      7

#define TRC_LOST_RECORDS_END    (TRC_GEN + 50)

enum {
    TRCE_SFLAG_SET_AD,
    TRCE_SFLAG_SET_A,
    TRCE_SFLAG_SHADOW_L1_GET_REF,
    TRCE_SFLAG_SHADOW_L1_PUT_REF,
    TRCE_SFLAG_L2_PROPAGATE,
    TRCE_SFLAG_SET_CHANGED,
    TRCE_SFLAG_SET_FLUSH,
    TRCE_SFLAG_SET_ERROR,
    TRCE_SFLAG_DEMOTE,
    TRCE_SFLAG_PROMOTE,
    TRCE_SFLAG_WRMAP,
    TRCE_SFLAG_WRMAP_GUESS_FOUND,
    TRCE_SFLAG_WRMAP_BRUTE_FORCE,
    TRCE_SFLAG_EARLY_UNSHADOW,
    TRCE_SFLAG_EMULATION_2ND_PT_WRITTEN,
    TRCE_SFLAG_EMULATION_LAST_FAILED,
    TRCE_SFLAG_EMULATE_FULL_PT,
    TRCE_SFLAG_PREALLOC_UNPIN,
    TRCE_SFLAG_PREALLOC_UNHOOK
};

#define TRC_HVM_OP_DESTROY_PROC (TRC_HVM_HANDLER + 0x100)
#endif
