#!/bin/sh

# config
binaries="bash mount umount cat mknod mkdir"	# required: some shell bits
binaries="$binaries xc_kexec"			# required: kexec stuff
binaries="$binaries ls rm grep dialog clear"	# required by select-kernel
binaries="$binaries resize"			# required by select-kernel
binaries="$binaries dmesg free ps"		# nice for diagnostics
binaries="$binaries uname sed cp touch mktemp"	# some scripts need this
binaries="$binaries pidofproc logger"  		# some scripts need this

optbin="mdrun mdadm lvm"			# optional stuff
optbin="$optbin dhcpcd ip modify_resolvconf"	# optional stuff

############################################################################

# setup
XEN_ROOT=$(pwd | sed -e 's|/[^/]*/[^/]*$||')
export PATH="${XEN_ROOT}/tools/xcutils:/sbin:/bin:/usr/sbin:/usr/bin:/usr/X11R6/bin"
export LD_LIBRARY_PATH="${XEN_ROOT}/tools/libxc"

# use lib64?
if ldd /bin/sh | grep -qe '/lib64/'; then
	LIB="/lib64"
else
	LIB="/lib"
fi

# static filelist entries
cat <<EOF
# directories
dir /etc              0755 0 0
dir /dev              0755 0 0
dir /dev/pts          0755 0 0
dir /dev/shm          1755 0 0
dir /tmp              1777 0 0

dir /proc             0755 0 0
dir /sys              0755 0 0
dir /root             0755 0 0
dir /mnt              0755 0 0

dir /bin              0755 0 0
slink /sbin bin       0777 0 0
dir $LIB              0755 0 0

dir /usr              0755 0 0
dir /var              0755 0 0
dir /var/tmp          1777 0 0
dir /var/run          0755 0 0
dir /var/lib          0755 0 0
dir /var/lib/dhcpcd   0755 0 0

# device nodes
nod /dev/console  0600 0 0 c 5 1
nod /dev/null     0666 0 0 c 1 3
nod /dev/kmsg     0600 0 0 c 1 11
nod /dev/md0      0600 0 0 b 9 0
nod /dev/md1      0600 0 0 b 9 1
nod /dev/md2      0600 0 0 b 9 2
nod /dev/md3      0600 0 0 b 9 3

# symlinks
slink /dev/stdin  fd/0     0777 0 0
slink /dev/stdout fd/1     0777 0 0
slink /dev/stderr fd/2     0777 0 0
slink /bin/sh     bash     0777 0 0
slink /dev/tty    console  0777 0 0

# files
file /etc/fstab /dev/null 0644 0 0

# kboot script
file /init $XEN_ROOT/tools/kboot/init 0755 0 0
file /bin/select-kernel $XEN_ROOT/tools/kboot/select-kernel 0755 0 0

# figlet eyecandy ;)
file /bin/figlet $XEN_ROOT/xen/tools/figlet/figlet 0755 0 0
file /xen.flf $XEN_ROOT/xen/tools/figlet/xen.flf 0644 0 0

EOF

# dynamic filelist entries
echo "# binaries"
ldd=""
for file in $binaries; do
	path="$(which $file)"
	if ! test -x "$path"; then
		echo "error: not found: binary $file"
		exit 1
	fi
	ldd="$ldd $path"
	echo "file /bin/$file $path 0755 0 0"
done
for file in $optbin; do
	path="$(which $file)"
	if ! test -x "$path"; then
		echo "info: not found: binary $file, skipping"
		continue
	fi
	ldd="$ldd $path"
	echo "file /bin/$file $path 0755 0 0"
done
echo

echo "# libraries"
libs=$(ldd $ldd | tr " \t" "\n" | grep -e "/lib.*so" | sort | uniq)
for lib in $libs; do
	echo "file $LIB/$(basename $lib) $lib 0755 0 0"
done
echo
